### ISSUE TITLE
Region color is overriding class colored character name

### ISSUE THREAD

**Issue by Xorag** [0xbs/premade-regions#2]
When looking at the group finder if you have a player from the MEX region apply, it always changes their name color to white, and for BZL it changes them to yellow - seems to only affect these multicolored region names.

**Comment by Rustyb0y** [comment]
> When looking at the group finder if you have a player from the MEX region apply, it always changes their name color to white, and for BZL it changes them to yellow - seems to only affect these multicolored region names.

I looked into it and currently I am unable to reproduce this issue.  Are you using any other addons/weakauras that modify group finder?

e.g.

![2021-01-22 22_34_16-World of Warcraft](https://user-images.githubusercontent.com/54157890/105486252-4f7f6980-5d02-11eb-9f03-2d0a1ce792ba.png)

![image](https://user-images.githubusercontent.com/54157890/105486373-7b9aea80-5d02-11eb-82f6-006309efb2b9.png)

**Comment by Xorag** [comment]
Well you can see there that the Brazilian player names are always yellow, and Mexican names are always white - overriding their class color

Only other addon I'm using is the main premade groups filter addon

**Comment by Xorag** [comment]
Here is a screenshot below with the applicants mouse-over'd - The only addon I have enabled here is premade regions.

![4](https://user-images.githubusercontent.com/42698965/105499859-15757f80-5c90-11eb-9af8-818c4348b22e.png)
![3](https://user-images.githubusercontent.com/42698965/105499862-15757f80-5c90-11eb-9c57-d10b182b8c67.png)
![2](https://user-images.githubusercontent.com/42698965/105499863-160e1600-5c90-11eb-98d3-73c0994ee626.png)
![1](https://user-images.githubusercontent.com/42698965/105499866-16a6ac80-5c90-11eb-832f-bc73788d01aa.png)

**Comment by 0xbs** [comment]
I assume the problem is in the following two lines. There is a color reset `|r` at the end, but the color from the middle letter does not seem to be resetted.

    ["mex"] = "|cFF006600M|cFFFFFFFFE|cFFCC3300X|r",
    ["bzl"] = "|cFF006600B|cFFFFFF00Z|cFF3333CCL|r",

@Rustyb0y could you try with the following, i.e. resetting the color with `|r` after each letter?

    ["mex"] = "|cFF006600M|r|cFFFFFFFFE|r|cFFCC3300X|r",
    ["bzl"] = "|cFF006600B|r|cFFFFFF00Z|r|cFF3333CCL|r",

**Comment by Rustyb0y** [comment]
@Xorag I see you were talking about the name text colour

@0xbs Yes that corrects the issue, I will update.
