### ISSUE TITLE
Semantic error while searching for CHI or LA.

### ISSUE THREAD

**Issue by Hazerre** [0xbs/premade-regions#3]
Problem: When trying to sort by the newly named CHI or LA regions the following error message is reported along with a failed search;

Semantic error in filter expression.
Expression did not evaluate to boolean, but to 'nil' of type nil.

Steps to recreate:
Open LFG menu. Go to Dungeons and Raids. Click Premade Groups. Click Find a group. Type in any valid search string including "and (CHI)" or "and (LA)" or "and (CHI or LA)" or "and (region == "CHI" or "LA") etc.

**Comment by Rustyb0y** [comment]
@Hazerre Short term fix.

Edit PremadeGroupsFilter\Plugins\PremadeRegions.lua

Replace lines 28 to 31

env.usp = false
env.usm = false
env.usc = false
env.use = false

with

env.la = false
env.chi = false

@0xbs Can you update this file with these changes please.

**Comment by 0xbs** [comment]
Will fix that tomorrow (CET time)

**Comment by 0xbs** [comment]
Now fixed in Premade Groups Filter
