### ISSUE TITLE
Azralon is in two server groups

### ISSUE THREAD

**Issue by gwenskey** [0xbs/premade-regions#8]
Can you remove Azralon from CHI group please, it's also listed in BZL group.

**Comment by gwenskey** [comment]
Ragnaros, Drakkari, Quel'Thalas, Nemesis, Goldrin, and Tol Barad are also double listed in CHI group as well as their repective MEX and BZL groups.

**Comment by 0xbs** [comment]
Lists are now up to date in version 2.0.3.

Also compared them to a [spreadsheet I found on the internet](https://docs.google.com/spreadsheets/d/1dG4zEolu71O94Rasrz_0zLs3BV7Q7vvahVXwks2Xr6o). Gallywix was duplicate as well.
